---
language: ruby
script: "bundle exec rake validate lint spec"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-2.3.3
env:
  - PUPPET_VERSION='~> 3.7.0'
  - PUPPET_VERSION='~> 3.8.0'
  - PUPPET_VERSION='~> 4.5.0'
  - PUPPET_VERSION='~> 4.6.0'
  - PUPPET_VERSION='~> 4.7.0'
  - PUPPET_VERSION='~> 4.8.0'
matrix:
  exclude:
    - rvm: 2.2
      env: PUPPET_VERSION='~> 3.7.0'
    - rvm: 2.2
      env: PUPPET_VERSION='~> 3.8.0'
    - rvm: ruby-2.3
      env: PUPPET_VERSION='~> 3.7.0'
    - rvm: ruby-2.3
      env: PUPPET_VERSION='~> 3.8.0'
